---
title: "qPCR_meta_coho_cut"
author: "Eily Allan"
date: "8/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(clock)
library(ggplot2)
```

## Import all kinds of fun data

```{r import data}
#modeled output
qpcr_cut <- read.csv(here("Output","models","cut_qpcr_model.csv"))
qpcr_coho <- read.csv(here("Output","models","coho_qpcr_model.csv"))

```


```{r plot qpcr}
cut <- qpcr_cut %>% 
  mutate(species="cut")

coho <- qpcr_coho %>% 
  mutate(species="coho")

both <- rbind(cut,coho) %>% 
  group_by(Sample) %>% 
  mutate(totDNA = sum(mean_corrected)) %>% 
  mutate(prop = mean_corrected/totDNA) %>% 
  separate(Sample, into=c("Month","Creek","Stn","Rep")) %>% 
  filter(Creek=="4Pad") 


ratio <- cut %>% 
  left_join(coho, by="Sample") %>% 
  mutate(ratio2 = mean_corrected.x/mean_corrected.y)  %>% 
  separate(Sample, into=c("Month","Creek","Stn","Rep")) %>% 
  filter(Creek=="4Pad") 

ggplot(ratio, aes(x=Month, y= ratio2, color=Stn)) +
  geom_point()
  #geom_bar(position="stack", stat="identity") +
  #facet_grid(~Stn)

ggplot(both, aes(x=Rep, y= prop, fill=species)) +
  geom_bar(position="stack", stat="identity") +
  facet_grid(~Stn~Month)

```

```{r compare coho and cutthroat}

coho_just_mean <- coho_modeled_conc %>% 
  unite(Sample, c(time,creek,station,biorep)) %>% 
  dplyr::select(-c(Plate,dilution,Adj_Vol, ci25_concentration_est, ci75_concentration_est)) %>% 
  mutate(species = "coho")

cut_just_mean <- cut_modeled_conc %>% 
  unite(Sample, c(time,creek,station,biorep)) %>% 
  dplyr::select(-c(Plate,dilution,Adj_Vol, ci25_concentration_est, ci75_concentration_est)) %>% 
  mutate(species = "cut") %>% 
  filter(Sample %in% coho_just_mean$Sample)

cut_coho <- rbind(cut_just_mean, coho_just_mean)

cut_coho_for_plot <- cut_coho %>%
  group_by(Sample) %>% 
  mutate(totalDNA = sum(mean_concentration_est)) %>% 
  mutate(propDNA = mean_concentration_est/totalDNA) %>% 
  separate(col = Sample, into = c("time", "creek", "station", "biol"), remove = FALSE) %>% 
  filter(creek == "4Pad") %>% 
    mutate(creek = case_when(creek == "4Pad" & station == "Dn" ~ "4Pad11",
                               creek == "4Pad" & station == "Up11" ~ "4Pad11",
                               TRUE ~ creek)) %>% 
    mutate(creek = case_when(creek == "4Pad" & station == "Up5" ~ "4Pad5",
                             TRUE ~ creek)) %>% 
    mutate(station = case_when(creek == "4Pad11" & station == "Up11" ~ "Up",
                             TRUE ~ station)) %>% 
    mutate(station = case_when(creek == "4Pad5" & station == "Up5" ~ "Up",
                             TRUE ~ station)) %>% 
  unite(Sample, c("time", "creek", "station", "biol"), remove = FALSE) 

qpcrplot <- ggplot(cut_coho_for_plot, aes(x = time, fill = species, y = propDNA)) +
    geom_col(position="stack") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_grid(~station ~biol ~creek) + 
  labs(title="qPCR data only Padden coho cutthroat")


### check out QM data
bayes_out <- readRDS(here("Output","metabarcoding","bayes_out.RDS"))

bayes_out_for_plot <- bayes_out$Bayes_estimates %>%
  rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to = "species") %>%
  separate(col = sample, into = c("time", "creek", "station", "biol"), remove = FALSE) %>% 
  filter(value > 0.001) %>% 
  filter(str_detect(creek, "4Pad")) %>% 
  filter(species == "Oncorhynchus clarkii" | species == "Oncorhynchus kisutch") %>% 
  group_by(sample) %>% 
  mutate(newtotal = sum(value)) %>% 
  mutate(newprop = value/newtotal) %>% 
  mutate(species = case_when(species == "Oncorhynchus clarkii" ~ "cut",
                             species == "Oncorhynchus kisutch" ~ "coho"))

miseqplot <- ggplot(bayes_out_for_plot, aes(x = time, fill = species, y = newprop)) +
    geom_col() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_grid(~station ~biol ~creek) + 
    labs(title="MiSeq data only Padden coho cutthroat")

library(gridExtra)

grid.arrange(qpcrplot, miseqplot)


qpcr_to_merge <- cut_coho_for_plot %>% 
  dplyr::select(c(Sample, species, propDNA)) %>% 
  mutate(method="qpcr") %>% 
  rename(prop = propDNA) 

miseq_to_merge <- bayes_out_for_plot %>% 
  rename(Sample = sample) %>% 
  rename(prop = newprop) %>%
  dplyr::select(c(Sample, species, prop)) %>% 
  mutate(method="qm") %>% 
  separate(col = Sample, into = c("time", "creek", "station", "biol"), remove = FALSE) %>%
  mutate(station = case_when(station == 1 ~ "Dn",
                                  station == 2 ~ "Up")) %>% 
  unite(Sample, c("time", "creek", "station", "biol"), remove = TRUE) 

compare_methods <- rbind(qpcr_to_merge, miseq_to_merge)

```