---
title: "process_miseq_data"
author: "Eily Allan"
date: "8/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rstan)
library(MCMCpack) #for rdirichelet function
library(here)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

source(here("Scripts","functions", "calibrate_metabarcoding.R")) 
```

## Import data

```{r read files}

#### Environmental data only for salmonids
enviro <- readRDS(here("Output", "metabarcoding", "envirodata.salmonids.for.qm.RDS"))
enviro <- enviro %>% 
    mutate(creek = case_when(creek == "4Pad" & station == "Dn" ~ "4Pad11",
                               creek == "4Pad" & station == "Up11" ~ "4Pad11",
                               TRUE ~ creek)) %>% 
    mutate(creek = case_when(creek == "4Pad" & station == "Up5" ~ "4Pad5",
                             TRUE ~ creek)) %>% 
    mutate(station = case_when(creek == "4Pad11" & station == "Up11" ~ "Up",
                             TRUE ~ station)) %>% 
    mutate(station = case_when(creek == "4Pad5" & station == "Up5" ~ "Up",
                             TRUE ~ station)) 

enviro <- enviro %>% 
  filter(creek == "4Pad11")

#### Rosetta stone data from newer run - using only tissue derived estimates without gBlock spike
mock <- readRDS(here("Input","mockcommunity","newmockdata_tissuenoGB.RDS"))

mock <- mock %>% 
  filter(InputType=="Tissue") %>% 
  filter(Genus == "Oncorhynchus") %>% 
  unite(CommTR, c(Community, Tech_Rep), remove=FALSE) %>% 
  filter(CommTR != "MC1_1")


# Prepare for stan model 
qmdata <- format_metabarcoding_data(enviro, mock)
stan_metabarcoding_data <- makeDesign(qmdata, N_pcr_cycles = 43)

```

## Run QM ML model to get proportions of species DNA corrected for amplification bias. 

```{r run QM ML model}

ML_out <- QM_likelihood(here("Scripts", "functions", "quant_metabar_rosetta_noSampleEta.stan"), stan_metabarcoding_data)

write_rds(ML_out, here("Output","metabarcoding","ML_out.RDS"))

ML_out$ML_estimates %>%
  rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to = "species") %>%
  separate(col = sample, into = c("time", "creek", "station", "biol"), remove = FALSE) %>% 
  mutate(station = case_when(station == 1 ~ "Down",
                                  station == 2 ~ "Up")) %>% 
  filter(value > 0.001) %>%
  ggplot(aes(x = time, fill = species, y = value)) +
    geom_col() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_grid(~station ~biol~creek)

```

## Run QM Bayesian model

```{r run QM Bayes model} 

bayes_out <- QM_bayes(here("Scripts", "functions", "quant_metabar_rosetta_noSampleEta.stan"), stan_metabarcoding_data)

write_rds(bayes_out, here("Output","metabarcoding","bayes_out.RDS"))

bayes_out$Bayes_estimates %>%
  rownames_to_column("sample") %>%
  pivot_longer(-sample, names_to = "species") %>%
  separate(col = sample, into = c("time", "creek", "station", "biol"), remove = FALSE) %>% 
  mutate(station = case_when(station == 1 ~ "Down",
                                  station == 2 ~ "Up")) %>% 
  filter(value > 0.001) %>%
  ggplot(aes(x = time, fill = species, y = value)) +
    geom_col() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    facet_grid(~station ~biol ~creek)

```
